[package]
name = "rusty_shell"
version = "0.1.0"
authors = ["Amandeep Singh <amandeep842.as@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
nix = "0.20.0"